package it.polimi.ingsw.view;

public enum Phase {
    LOGIN,
    COLOR,
    CHOOSE_SIDE_STARTING_CARD,
    GAMEFLOW,
    CHOOSE_SECRET_OBJECTIVE_CARD,
    WAIT,
    NUMBER_OF_PLAYERS,
    WAIT_NUMBER_OF_PLAYERS, WAIT_ALL_CHOOSEN_COLOR, WAIT_ALL_CHOSEN_STARTING_CARD, WAIT_ALL_CHOSEN_SECRET_CARD;
}
